import {
  FETCH_BOOKINGS_REQUEST,
  FETCH_BOOKINGS_SUCCESS,
  FETCH_BOOKINGS_FAILURE,
  DELETE_BOOKINGS_REQUEST,
  DELETE_BOOKINGS_SUCCESS,
  DELETE_BOOKINGS_FAILURE,
  DELETE_BOOKING_WITH_HASH,
  DELETE_BOOKINGS_WITH_HASH_SUCCESS,
  DELETE_BOOKINGS_WITH_HASH_FAILURE,
  POST_BOOKING,
  POST_BOOKING_SUCCESS,
  POST_BOOKING_FAILURE,
  POST_USER_DETAILS,
  SEND_EMAIL,
  UPDATE_BOOKING,
  SET_ACTIVE_PAGE,
  SET_PROGRESSBAR_VALUE
} from '../constants/actionTypes';

export const setActivePage = (page = '') => ({
  type: SET_ACTIVE_PAGE,
  page: { page }
});
