export const FETCH_BOOKINGS_REQUEST = 'FETCH_BOOKINGS_REQUEST';
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const FETCH_BOOKINGS_FAILURE = 'FETCH_BOOKINGS_FAILURE';

export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILURE = 'DELETE_BOOKING_FAILURE';

export const DELETE_BOOKING_WITH_HASH_REQUEST = 'DELETE_BOOKING_WITH_HASH_REQUEST';
export const DELETE_BOOKINGS_WITH_HASH_SUCCESS = 'DELETE_BOOKINGS_WITH_HASH_SUCCESS';
export const DELETE_BOOKINGS_WITH_HASH_FAILURE = 'DELETE_BOOKINGS_WITH_HASH_FAILURE';

export const POST_BOOKING_REQUEST = 'POST_BOOKING_REQUEST';
export const POST_BOOKING_SUCCESS = 'POST_BOOKING_SUCCESS';
export const POST_BOOKING_FAILURE = 'POST_BOOKING_FAILURE';

export const POST_USER_DETAILS_REQUEST = 'POST_USER_DETAILS_REQUEST';
export const POST_USER_DETAILS_SUCCESS = 'POST_USER_DETAILS_SUCCESS';
export const POST_USER_DETAILS_FAILURE = 'POST_USER_DETAILS_FAILURE';

export const SEND_EMAIL = 'SEND_EMAIL';

export const SAVE_BOOKING_REQUEST = 'SAVE_BOOKING_REQUEST';
export const SAVE_BOOKING_SUCCESS = 'SAVE_BOOKING_SUCCESS';

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_PROGRESSBAR_VALUE = 'SET_PROGRESSBAR_VALUE';

export const CHECK_WHICH_DATES_ARE_FULL = 'CHECK_WHICH_DATES_ARE_FULL';
export const SAVE_CONTROLLED_DATES = 'SAVE_CONTROLLED_DATES';
export const UPDATE_BOOKING_STATUS = 'UPDATE_BOOKING_STATUS';

export const VIEWSTATE_SET_DATA = 'VIEWSTATE_SET_DATA';
